### PR TITLE
support streamable

### PR DESCRIPTION
**Pull request by connorbrathwaite**
most likely have edge cases to be addressed, but a minimal implementation seems to be working (see: #7)

all feedback is welcome and encouraged. thanks!

### CODE REVIEW

**Comment by qrohlf** [comment]
just wanted to let you know that I'm traveling at the moment, but I'll take a look at this and possibly cut a release when I'm back in the US (mid-September)

**Comment by connorbrathwaite** [comment]
> just wanted to let you know that I'm traveling at the moment, but I'll take a look at this and possibly cut a release when I'm back in the US (mid-September)

grave digging this one as it's a personal convenience, any chance it could be merged?

**Comment by qrohlf** [comment]
Does streamable have a time limit on videos uploaded?

**Comment by connorbrathwaite** [comment]
> There is a 10 minute limit on video duration and a maximum file size of 1GB for direct file uploads.

**Comment by qrohlf** [comment]
Alright, seems reasonable enough. Eventually I'd like to add Slack-style thresholds on the filesize that will auto-play, but for now I'm not too worried.

**Comment by qrohlf** [comment]
Mind adding a Streamable test case to https://github.com/qrohlf/GifHub/issues/1?

**Pull request merged**
